sudo: required
language: generic 
services: 
  - docker

before_install:
  - docker build -t anabeldlw/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true anabeldlw/docker-react npm run test
